---
title: "Temporal Cox model"
author: "Hening Cui"
date: "5/9/2023"
output: 
  html_document:
   code_folding: hide
---
```{r, warning=FALSE, message=FALSE}
library(Seurat)
library(spacexr)
library(tidyverse)
library(spatstat)
library(nlme)
library(lgcp)
library(CAinterprTools)
library(sf)
library(concaveman)
library(ggplot2)
```

# loading dataset
```{r}
load(file= "/Users/cuihening/Desktop/shikun/seurat/robjs/chicken_visium.4.Robj")
```

```{r}
TM <- FetchData(object=chicken_visium,vars=c('TMSB4X','ident', 'orig.ident')) 
tmsb4x=cbind(cell = rownames(TM), TM) %>% 
  dplyr::rename(time = orig.ident) 
tmsb4x$is2=as.factor(ifelse(tmsb4x$ident==2,1,0))
```

The function to get coordinate
```{r}
getcoor=function(slice, time){
coords <- GetTissueCoordinates(chicken_visium, image= slice)
colnames(coords) <- c("x", "y")
coords <- cbind(cell = rownames(coords),coords)
coords$time = time
return(coords)
}
```

```{r}
coords_d4 = getcoor('slice1','D4')
coords_d10 = getcoor('slice1_D10-C1','D10')
coords_d7 = getcoor('slice1_D7-B1','D7')
coords_d14 = getcoor('slice1_D14-D1','D14')
```

Function for constuct ppp

```{r}
buildppp=function(dataset,markers){
X <- dataset$x
Y <- dataset$y
xrange <- range(X, na.rm=T)
print(xrange)
yrange <- range(Y, na.rm=T)
print(yrange)
ppppro =  ppp(X,Y,xrange,yrange,marks=markers)
return(ppppro)
}
```

# EDA 

## D4

```{r}
D4 = tmsb4x %>% 
  filter(time=='D4') %>% 
  merge(coords_d4, by="cell")  %>% 
  filter(x >= 385 &  y>=267 )  %>% 
  rename(Y=x, X=y) %>% 
  rename(x=X, y=Y) %>% 
  mutate(x=x-138, y=y-208) %>% 
  mutate(time=4)
summary(D4)
```

```{r}
xym= D4 %>% select(c("x","y")) 
pts <- st_as_sf(xym, coords=c('x','y'))
conc <- concaveman(pts)
ggplot() +
  geom_sf(data = conc, fill = NA)
```



```{r}
d4_owin= as.owin(as_Spatial(conc))
plot(d4_owin)
```


```{r}
D4_samppp =  ppp(D4$x,D4$y, c(0, 450),c(0,550), marks=D4$is2)
```

```{r}
D4_samppp =  ppp(D4$x,D4$y, window = d4_owin, marks=D4$is2)
```

```{r}
D4_ty2=D4 %>% 
  filter(is2==1)
D4_ty2p=ppp(D4_ty2$x,D4_ty2$y, c(0, 450),c(0,550))
```

```{r}
D4_ty2_owin=ppp(D4_ty2$x,D4_ty2$y, window = d4_owin)
```

```{r}
par(mfrow=c(1,2))
plot(D4_samppp, pch = 20,show.window=FALSE,cols=c("blue", "green"), legend=FALSE, main="D4 point",markscale = 0.1)
plot(density(D4_ty2_owin), main="D4 density")
```

```{r}
pixel=pixellate.ppp(D4_ty2_owin,fractional=TRUE)
plot(pixel)
```

```{r}
plot(as.im(density(D4_ty2_owin), fractional=TRUE))
```




```{r, fig.height=10, fig.width=12}
par(mfrow=c(1,2))
plot(D4_samppp, pch = 20,show.window=FALSE,cols=c("blue", "green"), legend=FALSE, main="D4 point",markscale = 0.1)
plot(density(D4_ty2p), main="D4 density")
```

```{r}
D4_fit =  kppm(D4_ty2p ~1, "LGCP")
D4_fit
```

```{r}
D4_fit =  kppm(D4_ty2_owin ~1, "LGCP")
D4_fit
```

```{r}
plot(predict.dppm(D4_fit))
```

### D7

```{r}
D7 = tmsb4x %>% 
  filter(time=='D7') %>% 
  merge(coords_d7, by="cell")  %>% 
  filter(x >= 255 &  y>=267 )  %>% 
  rename(Y=x, X=y) %>% 
  rename(x=X, y=Y) %>% 
  mutate(x=x-150, y=y-152) %>% 
  mutate(time=7)
summary(D7)
```

```{r}
xym= D7 %>% select(c("x","y")) 
pts <- st_as_sf(xym, coords=c('x','y'))
conc <- concaveman(pts)
ggplot() +
  geom_sf(data = conc, fill = NA)
```

```{r}
d7_owin= as.owin(as_Spatial(conc))
plot(d7_owin)
```
```{r}
D7_samppp =  ppp(D7$x,D7$y, window = d7_owin, marks=D7$is2)
```

```{r}
D7_ty2=D7 %>% 
  filter(is2==1)
D7_ty2p=ppp(D7_ty2$x,D7_ty2$y, window = d7_owin)
```

```{r, fig.height=10, fig.width=12}
par(mfrow=c(1,2))
plot(D7_samppp, pch = 20,show.window=FALSE, cols=c("blue", "green"), legend=FALSE, main="D7 point")
plot(density(D7_ty2p), main="D7 density")
```
```{r}
D7_fit =  kppm(D7_ty2p ~1, "LGCP")
D7_fit
```


### D10

```{r}
D10 = tmsb4x %>% 
  filter(time=='D10') %>% 
  merge(coords_d10, by="cell")  %>% 
  filter(x >= 193 &  y>=320)  %>% 
  rename(Y=x, X=y) %>% 
  rename(x=X, y=Y) %>% 
  mutate(x=x-217, y=y-128) %>% 
  mutate(time=10)
summary(D10)
```

```{r}
xym= D10 %>% select(c("x","y")) 
pts <- st_as_sf(xym, coords=c('x','y'))
conc <- concaveman(pts)
ggplot() +
  geom_sf(data = conc, fill = NA)
```

```{r}
d10_owin= as.owin(as_Spatial(conc))
plot(d10_owin)
```
```{r}
D10_samppp =ppp(D10$x,D10$y, window = d10_owin, marks=D10$is2)
```

```{r}
D10_ty2=D10 %>% 
  filter(is2==1)
D10_ty2p=ppp(D10_ty2$x,D10_ty2$y, window = d10_owin)
```

```{r, fig.height=10, fig.width=12}
par(mfrow=c(1,2))
plot(D10_samppp, pch = 20,show.window=FALSE, cols=c("blue", "green"), legend=FALSE, main="D10 point")
plot(density(D10_ty2p), main="D10 density")
```
```{r}
D10_fit =  kppm(D10_ty2p ~1, "LGCP")
D10_fit
```

## D14
```{r}
D14 = tmsb4x %>% 
  filter(time=='D14') %>% 
  merge(coords_d14, by="cell")  %>% 
  rename(Y=x, X=y) %>% 
  rename(x=X, y=Y) %>% 
  mutate(x=x-144, y=y-78) %>% 
  mutate(time=14)
summary(D14)
```

```{r}
xym= D14 %>% select(c("x","y")) 
pts <- st_as_sf(xym, coords=c('x','y'))
conc <- concaveman(pts)
ggplot() +
  geom_sf(data = conc, fill = NA)
```

```{r}
d14_owin= as.owin(as_Spatial(conc))
plot(d14_owin)
```

```{r}
D14_samppp =  ppp(D14$x,D14$y, window = d14_owin, marks=D14$is2)
```



```{r}
D14_ty2=D14 %>% 
  filter(is2==1)
D14_ty2p=ppp(D14_ty2$x,D14_ty2$y, window = d14_owin)
```

```{r, fig.height=10, fig.width=12}
par(mfrow=c(1,2))
plot(D14_samppp, pch = 20,show.window=FALSE, cols=c("blue", "green"), legend=FALSE, main="D14 point")
plot(density(D14_ty2p), main="D14 density")
```

```{r}
D14_fit =  kppm(D14_ty2p ~1, "LGCP")
D14_fit
```

## Spatstat replicate model
Create the list of all point
```{r}
time_ty2=solist(D4_ty2_owin,D7_ty2p, D10_ty2p, D14_ty2p)
time_ty2
sapply(time_ty2, npoints)
```

```{r}
plot.solist(time_ty2, main="The ty2 cell", main.panel=letters[1:4], legend=FALSE, equal.scales = TRUE, halign=TRUE, valign=TRUE)
```

Turn list into hyperframe
```{r}
hyoertime <- hyperframe(cell=time_ty2)
hyoertime$time=c(4,7,10,14)
```

```{r}
plot(hyoertime, quote(plot(density(cell), main=time)))
```

```{r}
try=mppm(cell~time, hyoertime)
```
test the model
```{r}
cdf.test.mppm(try, "y")
```


```{r}
plot.mppm(try, main="The ty2 cell", cif=TRUE,
                how="image")
```

```{r}
lurking(try, covariate = expression(time))
```


```{r}
sub_time=subfits(try)
```

```{r}
fitted_intensities <- predict.mppm(try)
```

```{r}
fitted_intensities2 <- predict.mppm(try,locations = D4_ty2_owin)
fitted_intensities2
```





```{r}
K_functions4 <-  Kinhom(D4_ty2_owin, ratio= TRUE)
K_functions7 <-  Kinhom(D7_ty2p, ratio= TRUE)
K_functions10 <-  Kinhom(D10_ty2p, ratio= TRUE)
K_functions14 <-  Kinhom(D14_ty2p, ratio= TRUE)
```

```{r}
Kcomb=pool(K_functions4,K_functions7,K_functions10,K_functions14)
```

```{r}
try=lgcp.estK(Kcomb)
```

```{r}
try
```

## Cox Spatial Temporal Model
prepare data
```{r}
temp= rbind(D4, D7, D10, D14) %>% 
  filter(ident==2) %>% 
  select(x,y,time, is2)
```

```{r}
temppx=ppx(temp)
plot(temppx)
```

```{r}
library("stpp")
```



```{r}
tlim=c(0,14)
```

```{r}
xyt <- stppp(list(data = temp, tlim = tlim, window = owin(c(0,450),c(0,550))))
```

```{r}
xyt <- integerise(xyt)
xyt
```

```{r}
den <- lambdaEst(xyt, axes = TRUE)
plot(den)
```
```{r}
sar <- spatialAtRisk(den)
sar
plot(sar)
```
```{r}
mut <- muEst(xyt)
mut
plot(mut)
```

```{r}
gin <- ginhomAverage(xyt, spatial.intensity = sar, temporal.intensity = mut)
plot(gin)
```

```{r}
kin <- KinhomAverage(xyt, spatial.intensity = sar, temporal.intensity = mut)
```



